# Generated by Django 6.0.2 on 2026-02-04 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('HO', 'Head Office (HO)'), ('ESTATE', 'Estate / Kebun')], max_length=10)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=20, unique=True, verbose_name='NIK')),
                ('full_name', models.CharField(max_length=150)),
                ('employee_type', models.CharField(choices=[('HARIAN', 'Buruh Harian'), ('STAFF', 'Staff Kantor'), ('MANDOR', 'Mandor')], default='HARIAN', max_length=10)),
                ('device_user_id', models.IntegerField(blank=True, help_text='ID User di mesin Fingerprint', null=True, unique=True)),
                ('telegram_user_id', models.CharField(blank=True, help_text='ID Telegram untuk Mandor', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPHA', 'Alpha / Mangkir')], default='HADIR', max_length=10)),
                ('verification_type', models.CharField(choices=[('FINGERPRINT', 'Mesin Fingerprint'), ('TELEGRAM_BOT', 'Telegram Bot')], max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Alasan izin/sakit atau catatan lain', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'timestamp'), name='unique_employee_timestamp')],
            },
        ),
    ]
