# Generated by Django 6.0.2 on 2026-02-04 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contoh: Kebun Alpha, Pabrik Kelapa Sawit', max_length=150)),
                ('code', models.CharField(help_text='Contoh: KBN-A, PKS, HO', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Work Location',
                'verbose_name_plural': 'Work Locations',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='verification_type',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='source_type',
            field=models.CharField(choices=[('FINGERPRINT', 'Fingerprint Machine'), ('TELEGRAM', 'Telegram / Spreadsheet')], default='FINGERPRINT', max_length=15),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='verification_method',
            field=models.CharField(choices=[('FINGER', 'Fingerprint'), ('PASSWORD', 'Password'), ('FACE', 'Face ID'), ('GPS', 'GPS Location'), ('MANUAL', 'Manual Input')], default='FINGER', max_length=20),
        ),
        migrations.CreateModel(
            name='SpreadsheetSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contoh: Rekap Absensi Kebun A', max_length=150)),
                ('spreadsheet_id', models.CharField(help_text='ID unik Google Sheet', max_length=150)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to='attendance.worklocation')),
            ],
            options={
                'verbose_name': 'Spreadsheet Source (Telegram)',
                'verbose_name_plural': 'Spreadsheet Sources (Telegram)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contoh: Mesin Pos 1', max_length=100)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.IntegerField(default=4370)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='attendance.worklocation')),
            ],
            options={
                'verbose_name': 'Fingerprint Device',
                'verbose_name_plural': 'Fingerprint Devices',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='captured_at',
            field=models.ForeignKey(blank=True, help_text='Lokasi fisik saat data diambil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_logs', to='attendance.worklocation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_base',
            field=models.ForeignKey(blank=True, help_text='Lokasi penempatan asli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_employees', to='attendance.worklocation'),
        ),
    ]
