# Generated by Django 6.0.2 on 2026-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_worklocation_remove_attendancelog_verification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='log_category',
            field=models.CharField(choices=[('MASUK', 'Masuk (05:00-08:30)'), ('CHECK1', 'Check 1 (09:00-11:00)'), ('ISTIRAHAT', 'Istirahat (11:30-13:30)'), ('CHECK2', 'Check 2 (14:00-15:45)'), ('PULANG', 'Pulang (>16:00)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Kategori waktu absensi', max_length=15),
        ),
    ]
