# Generated by Django 6.0.2 on 2026-02-05 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancelog_log_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama jadwal. Contoh: Shift Normal, Telegram Kebun', max_length=100)),
                ('code', models.CharField(help_text='Kode unik. Contoh: NORMAL, TG-KEBUN', max_length=20, unique=True)),
                ('clock_in', models.TimeField(help_text='Jam masuk utama')),
                ('clock_out', models.TimeField(help_text='Jam pulang utama')),
                ('break_start', models.TimeField(blank=True, help_text='Mulai istirahat', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Selesai istirahat', null=True)),
                ('scan_in_start', models.TimeField(blank=True, help_text='Awal window scan masuk', null=True)),
                ('scan_in_end', models.TimeField(blank=True, help_text='Akhir window scan masuk', null=True)),
                ('scan_out_start', models.TimeField(blank=True, help_text='Awal window scan pulang', null=True)),
                ('scan_out_end', models.TimeField(blank=True, help_text='Akhir window scan pulang', null=True)),
                ('late_tolerance', models.IntegerField(default=0, help_text='Toleransi keterlambatan (menit)')),
                ('enable_checkin_1', models.BooleanField(default=False, help_text='Aktifkan Checkpoint 1')),
                ('checkin_1_start', models.TimeField(blank=True, help_text='Awal jendela Checkin 1', null=True)),
                ('checkin_1_end', models.TimeField(blank=True, help_text='Akhir jendela Checkin 1', null=True)),
                ('enable_checkin_2', models.BooleanField(default=False, help_text='Aktifkan Checkpoint 2')),
                ('checkin_2_start', models.TimeField(blank=True, help_text='Awal jendela Checkin 2', null=True)),
                ('checkin_2_end', models.TimeField(blank=True, help_text='Akhir jendela Checkin 2', null=True)),
                ('allowed_radius', models.IntegerField(default=1500, help_text='Radius GPS yang diizinkan (meter)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='worklocation',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude koordinat lokasi', null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude koordinat lokasi', null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='log_category',
            field=models.CharField(choices=[('MASUK', 'Masuk'), ('CHECKPOINT_1', 'Checkpoint 1'), ('ISTIRAHAT', 'Istirahat'), ('CHECKPOINT_2', 'Checkpoint 2'), ('PULANG', 'Pulang'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Kategori waktu absensi', max_length=15),
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama pola shift. Contoh: Shift 5 Hari Kerja', max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_patterns', to='attendance.dailyschedule')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_patterns', to='attendance.dailyschedule')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday_patterns', to='attendance.dailyschedule')),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_patterns', to='attendance.dailyschedule')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_patterns', to='attendance.dailyschedule')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_patterns', to='attendance.dailyschedule')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_patterns', to='attendance.dailyschedule')),
            ],
            options={
                'verbose_name': 'Shift Pattern',
                'verbose_name_plural': 'Shift Patterns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(help_text='Tanggal mulai berlaku')),
                ('effective_to', models.DateField(blank=True, help_text='Tanggal berakhir (kosong = masih aktif)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='attendance.employee')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shiftpattern')),
            ],
            options={
                'verbose_name': 'Employee Shift Assignment',
                'verbose_name_plural': 'Employee Shift Assignments',
                'ordering': ['-effective_from'],
            },
        ),
    ]
