# Generated by Django 6.0.2 on 2026-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailyschedule_worklocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'Pendaftaran Baru',
                'verbose_name_plural': 'Pendaftaran Baru',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance.employee',),
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Karyawan', 'verbose_name_plural': 'Karyawan Master'},
        ),
        migrations.AddField(
            model_name='employee',
            name='imported_at',
            field=models.DateTimeField(blank=True, help_text='Tanggal data di-import', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='False = Data baru (butuh review). True = Data master valid.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(blank=True, help_text='Tanggal mulai bekerja', null=True),
        ),
    ]
