# Generated by Django 6.0.2 on 2026-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Nomor WA/HP untuk matching log Telegram', max_length=20, null=True),
        ),
    ]
