# Generated by Django 6.0.2 on 2026-02-06 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_phone_number_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('HRD', 'HRD / Manager'), ('ACCOUNTING', 'Accounting'), ('KERANI', 'Kerani (Admin Lapangan)')], default='KERANI', max_length=20)),
                ('assigned_location', models.ForeignKey(blank=True, help_text='Lokasi kerja utama (untuk filtering data)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.worklocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
