# Generated by Django 6.0.2 on 2026-02-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheetsource',
            name='employee_sheet_name',
            field=models.CharField(default='Data-Pegawai', help_text='Nama Sheet untuk Data Pegawai', max_length=100),
        ),
        migrations.AlterField(
            model_name='spreadsheetsource',
            name='sheet_name',
            field=models.CharField(default='Sheet1', help_text='Nama Sheet untuk Log Absensi', max_length=100),
        ),
    ]
