# Generated by Django 6.0.2 on 2026-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_spreadsheetsource_employee_sheet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='verification_method',
            field=models.CharField(choices=[('FINGER', 'Fingerprint'), ('PASSWORD', 'Password'), ('FACE', 'Face ID'), ('GPS', 'GPS Location'), ('MANUAL', 'Manual Input'), ('WA', 'WhatsApp / Telegram')], default='FINGER', max_length=20),
        ),
    ]
