# Generated by Django 6.0.2 on 2026-02-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancelog_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintdevice',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Waktu terakhir aktif/ping/sync', null=True),
        ),
        migrations.AddField(
            model_name='spreadsheetsource',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Waktu terakhir aktif/pull', null=True),
        ),
    ]
