# Generated by Django 6.0.2 on 2026-02-08 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_worklocation_level_worklocation_lft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(help_text='Tanggal efektif mutasi')),
                ('reason', models.TextField(blank=True, help_text='Alasan mutasi (opsional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Admin yang memproses mutasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_mutations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='attendance.employee')),
                ('new_location', models.ForeignKey(help_text='Lokasi tujuan setelah mutasi', on_delete=django.db.models.deletion.CASCADE, related_name='mutations_in', to='attendance.worklocation')),
                ('old_location', models.ForeignKey(help_text='Lokasi asal sebelum mutasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_out', to='attendance.worklocation')),
            ],
            options={
                'verbose_name': 'Employee Mutation',
                'verbose_name_plural': 'Employee Mutations',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
