# Generated by Django 6.0.2 on 2026-02-08 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_employee_mutation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Bulan periode (1-12)')),
                ('period_year', models.IntegerField(help_text='Tahun periode (Contoh: 2026)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Masih bisa diedit)'), ('SUBMITTED', 'Dikunci Kerani (Menunggu HRD)'), ('VERIFIED', 'Disetujui HRD'), ('REQ_REVISI', 'Permintaan Revisi'), ('REJECTED', 'Ditolak (Dikembalikan ke Draft)')], db_index=True, default='DRAFT', max_length=15)),
                ('version', models.IntegerField(default=0, help_text='Versi laporan (bertambah setiap revisi disetujui)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Waktu laporan dikunci oleh Kerani', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Waktu laporan diverifikasi oleh HRD', null=True)),
                ('notes', models.TextField(blank=True, help_text='Catatan revisi/penolakan/keterangan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Lokasi kerja untuk laporan ini', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='attendance.worklocation')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Kerani yang mengunci laporan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='HRD yang memverifikasi laporan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-period_year', '-period_month', 'location__code'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Laporan Dibuat'), ('SUBMIT', 'Dikunci/Submit oleh Kerani'), ('VERIFY', 'Diverifikasi oleh HRD'), ('REJECT', 'Ditolak oleh HRD'), ('REQUEST_REVISION', 'Permintaan Revisi'), ('REOPEN', 'Dibuka Kembali ke Draft'), ('UPDATE', 'Data Diperbarui')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, help_text='Status sebelum aksi', max_length=15, null=True)),
                ('new_status', models.CharField(blank=True, help_text='Status setelah aksi', max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Alasan/catatan untuk aksi ini', null=True)),
                ('actor', models.ForeignKey(help_text='User yang melakukan aksi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='attendance.monthlyreport')),
            ],
            options={
                'verbose_name': 'Report History',
                'verbose_name_plural': 'Report Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['period_year', 'period_month'], name='attendance__period__77b201_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['status'], name='attendance__status_3f3952_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('location', 'period_month', 'period_year')},
        ),
    ]
