# Generated by Django 6.0.2 on 2026-02-09 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_monthly_report_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('CUTI', 'Cuti Tahunan'), ('CUTI_KHUSUS', 'Cuti Khusus')], max_length=20)),
                ('start_date', models.DateField(help_text='Tanggal mulai izin/cuti')),
                ('end_date', models.DateField(help_text='Tanggal selesai izin/cuti')),
                ('notes', models.TextField(blank=True, help_text='Keterangan/alasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User yang menginput data ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Employee Leave',
                'verbose_name_plural': 'Employee Leaves',
                'ordering': ['-start_date'],
            },
        ),
    ]
