# Generated by Django 6.0.2 on 2026-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_employeeleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='overtime_tolerance',
            field=models.IntegerField(default=0, help_text='Toleransi lembur setelah jam pulang (menit). Contoh: 60 = lembur dihitung setelah 1 jam dari jam pulang.'),
        ),
    ]
