# Generated by Django 6.0.2 on 2026-02-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_add_overtime_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='attachment',
            field=models.ImageField(blank=True, help_text='Bukti foto/dokumen', null=True, upload_to='leaves/'),
        ),
    ]
