# Generated by Django 6.0.2 on 2026-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_employeeleave_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_method',
            field=models.CharField(choices=[('FINGERPRINT', 'Mesin Fingerprint'), ('WHATSAPP', 'WhatsApp / Telegram'), ('MANUAL', 'Manual / Lainnya')], default='FINGERPRINT', help_text='Metode absensi utama', max_length=20),
        ),
    ]
