# Generated by Django 6.0.2 on 2026-02-11 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_employee_attendance_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User yang terakhir mengubah data (real-time from signals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
