# Generated by Django 6.0.2 on 2026-02-12 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_monthlyreport_last_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Waktu pembayaran disetujui', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Accounting/Manager yang menyetujui pembayaran', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Masih bisa diedit)'), ('SUBMITTED', 'Dikunci Kerani (Menunggu HRD)'), ('VERIFIED', 'Disetujui HRD (Siap Bayar)'), ('APPROVED', 'Disetujui / Lunas (Final)'), ('REQ_REVISI', 'Permintaan Revisi'), ('REQ_UNLOCK', 'Permintaan Buka Kunci (Kerani)'), ('REJECTED', 'Ditolak (Dikembalikan ke Draft)')], db_index=True, default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Laporan Dibuat'), ('SUBMIT', 'Dikunci/Submit oleh Kerani'), ('VERIFIED', 'Diverifikasi HRD (Siap Bayar)'), ('APPROVED', 'Disetujui / Lunas (Final)'), ('REJECTED', 'Ditolak (Perlu Revisi)'), ('REQUEST_REVISION', 'Permintaan Revisi'), ('REQUEST_UNLOCK', 'Permintaan Buka Kunci'), ('APPROVE_UNLOCK', 'Menyetujui Buka Kunci'), ('REJECT_UNLOCK', 'Menolak Buka Kunci'), ('APPROVE_PAYMENT', 'Menyetujui Pembayaran (Final)'), ('REOPEN', 'Dibuka Kembali ke Draft'), ('UPDATE', 'Data Diperbarui')], db_index=True, max_length=20),
        ),
    ]
