# Generated by Django 6.0.2 on 2026-02-13 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_monthlyreport_approved_at_monthlyreport_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama Mesin (cth: Pos Satpam)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address Mesin (cth: 192.168.1.201)')),
                ('port', models.IntegerField(default=4370, help_text='Port Mesin (Default ZKTeco: 4370)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='attendance.worklocation')),
            ],
            options={
                'verbose_name': 'Mesin Absensi',
                'verbose_name_plural': 'Daftar Mesin Absensi',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Berhasil'), ('FAILED', 'Gagal'), ('PARTIAL', 'Sebagian')], max_length=20)),
                ('records_count', models.IntegerField(default=0, help_text='Jumlah data yang ditarik')),
                ('log_message', models.TextField(blank=True, help_text='Detail log atau pesan error')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='attendance.attendancemachine')),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi',
                'verbose_name_plural': 'Log Sinkronisasi',
                'ordering': ['-timestamp'],
            },
        ),
    ]
