# Generated by Django 6.0.2 on 2026-02-13 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendancemachine_synclog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprintdevice',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='fingerprintdevice',
            name='auto_sync_time',
            field=models.TimeField(blank=True, help_text='Waktu sinkronisasi otomatis (HH:MM)', null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdevice',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Waktu terakhir aktif/ping/sync', null=True),
        ),
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_machines', to='attendance.worklocation'),
        ),
    ]
