# Generated by Django 6.0.2 on 2026-02-13 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remove_fingerprintdevice_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemachine',
            name='auto_sync_time',
            field=models.TimeField(blank=True, help_text='Waktu sinkronisasi otomatis (HH:MM)', null=True),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_configs', to='attendance.worklocation'),
        ),
    ]
