# Generated by Django 6.0.2 on 2026-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_attendancemachine_auto_sync_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('DIREKSI', 'Direksi'), ('KARYAWAN', 'Karyawan'), ('HARIAN', 'Buruh Harian')], default='HARIAN', max_length=10),
        ),
    ]
