# Generated by Django 6.0.2 on 2026-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_employee_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location_type',
            field=models.CharField(choices=[('HO', 'Head Office (HO)'), ('ESTATE', 'Estate / Kebun'), ('MILL', 'Mill / PKS')], max_length=10),
        ),
    ]
