# Generated by Django 6.0.2 on 2026-02-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_department_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='assigned_department',
            field=models.ForeignKey(blank=True, help_text='Departemen (untuk Admin Dept)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('HRD', 'HRD / Manager'), ('SUPERVISOR', 'Supervisor (Head of Location)'), ('ACCOUNTING', 'Accounting'), ('KERANI', 'Kerani (Admin Lapangan)'), ('DEPT_ADMIN', 'Admin Departemen')], default='KERANI', max_length=20),
        ),
    ]
