# Generated by Django 6.0.2 on 2026-02-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_accesslog_historicalattendancelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='verification_time',
            field=models.DateTimeField(blank=True, help_text='Waktu verifikasi manual/sinkronisasi', null=True),
        ),
        migrations.AddField(
            model_name='historicalattendancelog',
            name='verification_time',
            field=models.DateTimeField(blank=True, help_text='Waktu verifikasi manual/sinkronisasi', null=True),
        ),
    ]
