# Generated by Django 6.0.2 on 2026-02-16 14:15

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_attendancelog_verification_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_shift_worker',
            field=models.BooleanField(default=False, help_text='Jika dicentang, sistem akan mengecek tabel Daily Roster untuk jadwal orang ini.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_shift_worker',
            field=models.BooleanField(default=False, help_text='Jika dicentang, sistem akan mengecek tabel Daily Roster untuk jadwal orang ini.'),
        ),
        migrations.CreateModel(
            name='HistoricalDailyShiftAssignment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('date', models.DateField(help_text='Tanggal spesifik assignment')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.dailyschedule')),
            ],
            options={
                'verbose_name': 'historical Daily Shift Assignment (Roster)',
                'verbose_name_plural': 'historical Daily Shift Assignments (Roster)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DailyShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Tanggal spesifik assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='attendance.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='attendance.dailyschedule')),
            ],
            options={
                'verbose_name': 'Daily Shift Assignment (Roster)',
                'verbose_name_plural': 'Daily Shift Assignments (Roster)',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_f6fc1f_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
