# Generated by Django 6.0.2 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_employee_is_shift_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='excuse_reason',
            field=models.CharField(blank=True, help_text='Alasan pemakluman spesifik', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_excused',
            field=models.BooleanField(default=False, help_text='Keterlambatan/pulang cepat dimaklumi'),
        ),
        migrations.AddField(
            model_name='historicalattendancelog',
            name='excuse_reason',
            field=models.CharField(blank=True, help_text='Alasan pemakluman spesifik', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalattendancelog',
            name='is_excused',
            field=models.BooleanField(default=False, help_text='Keterlambatan/pulang cepat dimaklumi'),
        ),
    ]
