# Generated by Django 6.0.2 on 2026-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_attendancelog_excuse_reason_attendancelog_is_excused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_nik',
            field=models.CharField(blank=True, help_text='NIK resmi dari perusahaan', max_length=50, null=True, verbose_name='NIK Perusahaan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Jabatan saat ini. Contoh: Admin', max_length=100, null=True, verbose_name='Jabatan'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='company_nik',
            field=models.CharField(blank=True, help_text='NIK resmi dari perusahaan', max_length=50, null=True, verbose_name='NIK Perusahaan'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='position',
            field=models.CharField(blank=True, help_text='Jabatan saat ini. Contoh: Admin', max_length=100, null=True, verbose_name='Jabatan'),
        ),
    ]
