# Generated by Django 6.0.4 on 2026-04-17 09:19

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_employee_company_nik_employee_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSynergyMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_name', models.CharField(help_text='Nama Jabatan, cth: Staff Akunting', max_length=100, unique=True)),
                ('ideal_primary_traits', models.CharField(help_text='Cth: Melankolis, Plegmatis', max_length=100)),
                ('warning_primary_traits', models.CharField(help_text='Karakter yang butuh pendampingan ekstra di posisi ini. Cth: Sanguinis', max_length=100)),
            ],
            options={
                'verbose_name': 'Pemetaan Sinergi Posisi',
                'verbose_name_plural': 'Pemetaan Sinergi Posisi',
            },
        ),
        migrations.CreateModel(
            name='TraitDictionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trait_name', models.CharField(help_text='Cth: Sanguinis', max_length=50, unique=True)),
                ('core_strengths', models.TextField(help_text='Peluang Tumbuh / Kekuatan Utama')),
                ('development_areas', models.TextField(help_text='Area Pengembangan (Kelemahan)')),
                ('manager_coaching_tips', models.TextField(help_text='Tips Pembinaan untuk Atasan (Action Plan)')),
            ],
            options={
                'verbose_name': 'Kamus Tipe Karakter',
                'verbose_name_plural': 'Kamus Tipe Karakter',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPersonalityTest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('test_date', models.DateField(help_text='Tanggal Tes Dilakukan')),
                ('sanguine_score', models.FloatField(default=0)),
                ('melancholic_score', models.FloatField(default=0)),
                ('choleric_score', models.FloatField(default=0)),
                ('phlegmatic_score', models.FloatField(default=0)),
                ('sanguine_maturity', models.FloatField(default=0, help_text='% Kematangan Sanguinis')),
                ('melancholic_maturity', models.FloatField(default=0, help_text='% Kematangan Melankolis')),
                ('choleric_maturity', models.FloatField(default=0, help_text='% Kematangan Koleris')),
                ('phlegmatic_maturity', models.FloatField(default=0, help_text='% Kematangan Plegmatis')),
                ('primary_trait', models.CharField(blank=True, max_length=50)),
                ('secondary_trait', models.CharField(blank=True, max_length=50)),
                ('synergy_score', models.FloatField(default=0, help_text='Persentase Kecocokan dengan Posisi Saat Ini')),
                ('raw_responses', models.JSONField(blank=True, default=dict, help_text='Penyimpanan 40 poin indikator dalam bentuk Dictionary JSON')),
                ('consultant_notes', models.TextField(blank=True, help_text='Catatan manual khusus dari konsultan')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Hasil Psikotes (Talent Dev)',
                'verbose_name_plural': 'historical Hasil Psikotes (Talent Dev)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_date', models.DateField(help_text='Tanggal Tes Dilakukan')),
                ('sanguine_score', models.FloatField(default=0)),
                ('melancholic_score', models.FloatField(default=0)),
                ('choleric_score', models.FloatField(default=0)),
                ('phlegmatic_score', models.FloatField(default=0)),
                ('sanguine_maturity', models.FloatField(default=0, help_text='% Kematangan Sanguinis')),
                ('melancholic_maturity', models.FloatField(default=0, help_text='% Kematangan Melankolis')),
                ('choleric_maturity', models.FloatField(default=0, help_text='% Kematangan Koleris')),
                ('phlegmatic_maturity', models.FloatField(default=0, help_text='% Kematangan Plegmatis')),
                ('primary_trait', models.CharField(blank=True, max_length=50)),
                ('secondary_trait', models.CharField(blank=True, max_length=50)),
                ('synergy_score', models.FloatField(default=0, help_text='Persentase Kecocokan dengan Posisi Saat Ini')),
                ('raw_responses', models.JSONField(blank=True, default=dict, help_text='Penyimpanan 40 poin indikator dalam bentuk Dictionary JSON')),
                ('consultant_notes', models.TextField(blank=True, help_text='Catatan manual khusus dari konsultan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality_profile', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Hasil Psikotes (Talent Dev)',
                'verbose_name_plural': 'Hasil Psikotes (Talent Dev)',
                'ordering': ['-test_date'],
            },
        ),
    ]
