# Generated by Django 6.0.4 on 2026-04-17 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_rolesynergymaster_traitdictionary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_text', models.CharField(max_length=255, verbose_name='Teks Indikator (Contoh: Mudah Bergaul)')),
                ('category', models.CharField(choices=[('S', 'Sanguinis'), ('M', 'Melankolis'), ('K', 'Koleris'), ('P', 'Plegmatis'), ('JJ', 'Jujur'), ('TJ', 'Tanggung Jawab')], max_length=2, verbose_name='Kategori Induk')),
                ('kind', models.CharField(choices=[('POS', 'Positif (Kekuatan)'), ('NEG', 'Negatif (Kelemahan) / Netral')], max_length=3, verbose_name='Sifat / Jenis')),
                ('weight', models.FloatField(default=1.0, verbose_name='Bobot Pengali')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampil di Form?')),
            ],
            options={
                'verbose_name': 'Sub-Karakter (Form Builder)',
                'verbose_name_plural': 'Bank Soal / Sub-Karakter',
                'ordering': ['category', 'kind', 'indicator_text'],
            },
        ),
        migrations.AddField(
            model_name='historicalpersonalitytest',
            name='honesty_score',
            field=models.FloatField(default=0, help_text='Nilai Jujur (JJ)'),
        ),
        migrations.AddField(
            model_name='historicalpersonalitytest',
            name='responsibility_score',
            field=models.FloatField(default=0, help_text='Nilai Tanggung Jawab (TJ)'),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='honesty_score',
            field=models.FloatField(default=0, help_text='Nilai Jujur (JJ)'),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='responsibility_score',
            field=models.FloatField(default=0, help_text='Nilai Tanggung Jawab (TJ)'),
        ),
    ]
