# Generated by Django 6.0.4 on 2026-04-18 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_personalityindicator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Golongan Darah'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Golongan Darah'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='historicalpersonalitytest',
            name='evaluator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
