# Generated by Django 6.0.4 on 2026-04-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_employee_blood_type_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('HRD', 'HRD / Manager'), ('SUPERVISOR', 'Supervisor (Head of Location)'), ('ACCOUNTING', 'Accounting'), ('KERANI', 'Kerani (Admin Lapangan)'), ('DEPT_ADMIN', 'Admin Departemen'), ('PENGUJI', 'Penguji (Assessor)')], default='KERANI', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalitytest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality_tests', to='attendance.employee'),
        ),
    ]
