# Generated by Django 6.0.4 on 2026-04-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_alter_employeeprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonalitytest',
            name='input_source',
            field=models.CharField(choices=[('MANUAL', 'Form Manual'), ('EXCEL', 'Import Excel')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='input_source',
            field=models.CharField(choices=[('MANUAL', 'Form Manual'), ('EXCEL', 'Import Excel')], default='MANUAL', max_length=20),
        ),
    ]
